### ISSUE TITLE
bash upgrade_to_8.sh failing for  mate-desktop-environment-core

### ISSUE THREAD

**Issue by raonyguimaraes** [Bio-Linux/build-bio-linux#1]
Hi there,

I was trying to install last version of Biolinux 8.0.8 and I'm getting this error while running:

 sudo bash upgrade_to_8.sh 

dpkg: error processing archive /var/cache/apt/archives/bio-linux-mate-desktop_1.8.0+bl3_all.deb (--unpack):
 trying to overwrite '/usr/share/glib-2.0/schemas/mate-ubuntu.gschema.override', which is also in package mate-desktop-environment-core 1.8.0+9~trusty1

Errors were encountered while processing:
 /var/cache/apt/archives/bio-linux-mate-desktop_1.8.0+bl3_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

I think this might be because I had Ubuntu Mate ppas already installed. I think you could consider adding the proper ppas for this packages:

http://www.omgubuntu.co.uk/2014/08/install-mate-desktop-ubuntu-14-04-lts

**Comment by tony-travis** [comment]
On 27/09/17 13:44, Raony Guimarães Correa Do Carmo Lisboa Cardenas wrote:
> Hi there,
> 
> I was trying to install last version of Biolinux 8.0.8 and I'm getting
> this error while running:
> 
> sudo bash upgrade_to_8.sh

Hi, Raony.

Do you mean that you're trying to upgrade an existing Ubuntu 14.04 LTS
to Bio-Linux?

The "upgrade_to_8.sh" script is part of the Ubuntu 14.04 remastering
pipeline and is normally run in a chroot of an Ubuntu 14.04 root
filesystem extracted from the .iso downloaded from the Ubuntu website.

Are you following Tim's instructions for Bio-Linux 8.0.7 from here?

> http://environmentalomics.org/bio-linux-installation/

If so, you should be using "upgrade8.sh", not "upgrade_to_8.sh":

> wget http://nebc.nerc.ac.uk/downloads/bl8_only/upgrade8.sh
> sudo bash upgrade8.sh

The "upgrade8.sh" file contains "shar" archives, including one for
"upgrade_to_8.sh" and other files needed for the upgrade process.

> dpkg: error processing archive
> /var/cache/apt/archives/bio-linux-mate-desktop_1.8.0+bl3_all.deb (--unpack):
> trying to overwrite
> '/usr/share/glib-2.0/schemas/mate-ubuntu.gschema.override', which is
> also in package mate-desktop-environment-core 1.8.0+9~trusty1
> 
> Errors were encountered while processing:
> /var/cache/apt/archives/bio-linux-mate-desktop_1.8.0+bl3_all.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 
> I think this might be because I had Ubuntu Mate ppas already installed.
> I think you could consider adding the proper ppas for this packages:

You can use "upgrade8.sh" to upgrade an existing Ubuntu 14.04 instance,
if you want, as long as no conflicting packages are installed. However,
"upgrade8.sh" is normally used to upgrade a 'vanilla' chroot as part of
the Ubuntu 14.04 LTS remastering pipeline.

You're right, of course, that it would be better to use the “Ubuntu MATE
Developers” team PPA but that was not available when Bio-Linux 8.0.7 was
released. We've only done the Bio-Linux 8.0.8 point release to update
the kernel and packages in the .iso file. Other work will be done as
part of the Bio-Linux 9.0.0 upgrade: I plan to use Ubuntu-MATE 16.04 or
18.04 as the base distribution for that, and use their version of MATE.

HTH,

  Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        mailto:tony.travis@minke-informatics.co.uk
